export const SECTIONS = [
    {
      id: 'work',
      name: 'Work',
      subtitle: 'Experience & Internships',
      route: '/work',
      position: [4.2, 0.5, 0],
      color: '#00d4ff',
      glowColor: '#00d4ff',
      orbitRadius: 4.2,
      orbitSpeed: 0.18,
      orbitPhase: 0,
      icon: '◈',
      description: 'Professional journey through tech',
    },
    {
      id: 'projects',
      name: 'Projects',
      subtitle: 'Built From Scratch',
      route: '/projects',
      position: [0, 4.2, 0.5],
      color: '#00ff88',
      glowColor: '#00ff88',
      orbitRadius: 4.2,
      orbitSpeed: 0.14,
      orbitPhase: Math.PI / 2,
      icon: '◉',
      description: 'Code that lives in the real world',
    },
    {
      id: 'life',
      name: 'Life',
      subtitle: 'Beyond the Screen',
      route: '/life',
      position: [-4.2, 0, -0.5],
      color: '#ff6b6b',
      glowColor: '#ff6b6b',
      orbitRadius: 4.2,
      orbitSpeed: 0.22,
      orbitPhase: Math.PI,
      icon: '◎',
      description: 'Hobbies, travels, and moments',
    },
    {
      id: 'education',
      name: 'Education',
      subtitle: 'Knowledge Acquired',
      route: '/education',
      position: [0, -4.2, 0],
      color: '#ffaa00',
      glowColor: '#ffaa00',
      orbitRadius: 4.2,
      orbitSpeed: 0.16,
      orbitPhase: (3 * Math.PI) / 2,
      icon: '◇',
      description: 'Academic foundations & growth',
    },
  ]
  
  export const CAMERA_POSITIONS = {
    home: [0, 2, 10],
    zoomed: [0, 1.5, 7],
    entering: [0, 0, 3],
  }